data:
  train_csv: ""
  tune_csv: ""
  test_csv: ""

output_dir: "output" # output directory
experiment_name: ""

task: "classification" # task type: classification, regression, survival

num_classes: 2 # number of classes for classification task
label_name: "label"
label_mapping:

features_dir:

model:
  batch_size: 1
  embed_dim: 1024
  hidden_dim: 256
  dropout: 0.0
  gated: false # use gated attention mechanism

training:
  nepochs: 100
  batch_size: 1
  gradient_accumulation: 32

tuning:
  batch_size: 1
  tune_every: 1

testing:
  retrieve_checkpoint: "best"

optim:
  name: "adam"
  lr: 0.0002
  wd: 1e-5
  lr_scheduler:
    name: "step"
    step_size: 20
    gamma: 0.5

early_stopping:
  enable: False
  tracking: "loss"
  min_max: "min"
  patience: 10
  min_epoch: 30
  save_all: False

speed:
  num_workers: 8 # number of workers for tiling slides

wandb:
  enable: false
  project: "" # wandb project name
  username: "" # wandb username
  exp_name: "" # wandb experiment name
  tags: [] # wandb tags
  dir: "/home/user/"
  group: